name: Add git tag to Linear ticket on merge
on:
  push:
    branches:
      - master
jobs:
  Test-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action
        uses: nikitakalpakovski-metergram/linear-tag-on-merge@1.1
        id: hello
        with:
          who-to-greet: "The greetee"
